version: '2'

services:

### PHP-FPM Container #######################################

    php7:
        container_name: php7
        build:
            context: ./php7
        volumes_from:
            - volumes_source
        expose:
            - "9000"
            
### Nginx Server Container ##################################
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            args:
                - PHP7_UPSTREAM=php7
        volumes_from:
            - volumes_source
        ports:
            - "80:80"
        links:
            - php7

### phpMyAdmin Container ####################################

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8083:80"
        links:
            - "mariadb:db"

### MySQL Container #########################################

    mariadb:
        container_name: mariadb
        build: ./mariadb
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: lotto
            MYSQL_USER: the_lotto
            MYSQL_PASSWORD: lotto@2017
            MYSQL_ROOT_PASSWORD: thelotto@2017

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/mysql:/var/lib/mysql

### Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ./workspace/:/var/www/html
